# Generated by Django 6.0 on 2025-12-26 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('warrior', 'Воин'), ('paladin', 'Паладин'), ('hunter', 'Охотник'), ('rogue', 'Разбойник'), ('priest', 'Жрец'), ('death_knight', 'Рыцарь смерти'), ('shaman', 'Шаман'), ('mage', 'Маг'), ('warlock', 'Чернокнижник'), ('monk', 'Монах'), ('druid', 'Друид'), ('demon_hunter', 'Охотник на демонов'), ('evoker', 'Пробудитель')], max_length=50, unique=True, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('human', 'Человек'), ('dwarf', 'Дворф'), ('night_elf', 'Ночной эльф'), ('gnome', 'Гном'), ('draenei', 'Дреней'), ('worgen', 'Ворген'), ('void_elf', 'Эльф Бездны'), ('lightforged_draenei', 'Озаренный дреней'), ('dark_iron_dwarf', 'Дворф из клана Черного Железа'), ('kul_tiran', 'Култирасец'), ('mechagnome', 'Мехагном'), ('pandaren_a', 'Пандарен'), ('dracthyr_a', 'Драктир'), ('earthen_a', 'Земельники'), ('orc', 'Орк'), ('undead', 'Нежить'), ('tauren', 'Таурен'), ('troll', 'Тролль'), ('blood_elf', 'Эльф крови'), ('goblin', 'Гоблин'), ('nightborne', 'Ночнорожденный'), ('highmountain_tauren', 'Таурен Крутогорья'), ('maghar_orc', 'Магхарский орк'), ('zandalari_troll', 'Зандаларский тролль'), ('vulpera', 'Вульпера'), ('pandaren', 'Пандарен'), ('dracthyr', 'Драктир'), ('earthen', 'Земельники')], max_length=50, unique=True, verbose_name='Раса')),
                ('faction', models.CharField(choices=[('alliance', 'Альянс'), ('horde', 'Орда')], max_length=10, verbose_name='Фракция')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Специализация')),
                ('role', models.CharField(choices=[('tank', 'Танк'), ('healer', 'Хилер'), ('melee', 'Ближний бой'), ('ranged', 'Дальний бой')], max_length=10, verbose_name='Роль')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='character.characterclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'unique_together': {('character_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='2-16 символов', max_length=16, verbose_name='Имя персонажа')),
                ('faction', models.CharField(choices=[('alliance', 'Альянс'), ('horde', 'Орда')], max_length=10, verbose_name='Фракция')),
                ('item_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень предметов')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной персонаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='character.characterclass', verbose_name='Класс')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='character.race', verbose_name='Раса')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='character.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
